import type { AgentToolDefinition } from '../model-provider.js';
import type { ExcelSheetSpec, ParsedTableData, RichDocxSection } from '../office-engine.js';
import type { IToolHandler, ToolContext } from './tool-interface.js';

export class ProcessExcelToolHandler implements IToolHandler {
  public readonly name = 'office.process_excel';
  public readonly definition: AgentToolDefinition = {
    name: 'office.process_excel',
    description: '读取工作区内的 CSV/XLSX 数据表格，进行数值求和/统计计算，或根据自定义规格生成带动态求和公式的 Excel 工作簿 (.xlsx)',
    risk: 'write',
    requiresApproval: true,
    parameters: {
      type: 'object',
      properties: {
        source: { type: 'string', description: '数据源文件相对路径（如 data.csv）' },
        target: { type: 'string', description: '生成的目标 Excel 文件名（如 sales-summary.xlsx）' },
        title: { type: 'string', description: '工作簿标题' },
        sheets: {
          type: 'array',
          description: '可选的自定义工作表定义列表。如果不传，则自动读取源数据动态汇总生成',
        },
      },
    },
  };

  public canHandle(toolName: string): boolean {
    return toolName === this.name;
  }

  public async execute(
    _toolName: string,
    args: Record<string, unknown>,
    context: ToolContext,
  ): Promise<string> {
    const artifactName = (args.target as string) || 'sales-summary.xlsx';
    const customSheets = Array.isArray(args.sheets) ? (args.sheets as ExcelSheetSpec[]) : undefined;
    const title = (args.title as string) || '数据汇总表';

    let workbook: Buffer;
    if (customSheets && customSheets.length > 0) {
      workbook = await context.officeEngine.createExcelWorkbook({
        title,
        sheets: customSheets,
      });
    } else {
      const requestedSource = (args.source as string) || (args.path as string);
      let sourceFile = requestedSource;
      if (!sourceFile) {
        // 动态扫描工作区中可用的表格文件 (.csv / .xlsx)
        const allFiles = context.sandbox.listFiles();
        const tableCandidates = allFiles.filter((f) => f.endsWith('.csv') || f.endsWith('.xlsx'));
        const candidate = tableCandidates[0];
        if (candidate) {
          sourceFile = candidate;
        } else {
          return `[执行失败] 工作区中未找到任何 CSV 或 XLSX 数据源表格，请先指定 source 参数或在工作区导入数据。`;
        }
      }

      if (!context.sandbox.hasFile(sourceFile)) {
        return `[执行失败] 数据源文件不存在: ${sourceFile}。当前工作区文件列表: ${context.sandbox.listFiles().join(', ')}`;
      }

      const type = sourceFile.endsWith('.xlsx') ? 'xlsx' : 'csv';
      const tableData = await context.officeEngine.readTableData(
        context.sandbox.readFileBuffer(sourceFile),
        type,
      );

      if (!tableData || tableData.rows.length === 0) {
        return `[执行失败] 数据源文件 ${sourceFile} 中未解析到有效数据行，无法生成汇总表。`;
      }

      const columns = tableData.headers.map((h) => ({ header: h.toUpperCase(), key: h }));
      const rows = tableData.rows;

      workbook = await context.officeEngine.createExcelWorkbook({
        title,
        sheets: [{ name: '数据汇总', columns, rows, includeTotalRow: true }],
      });
    }

    context.sandbox.writeArtifactBuffer(artifactName, workbook);
    context.verifyArtifact(context.thread.id, artifactName);
    return `成功生成带动态公式的高保真 Excel 工作簿：${artifactName}（已完成物理证据链校验）`;
  }
}

export class GenerateWordReportToolHandler implements IToolHandler {
  public readonly name = 'office.generate_word_report';
  public readonly definition: AgentToolDefinition = {
    name: 'office.generate_word_report',
    description: '根据材料或结构化内容生成包含主标题、分节正文与格式化对比表格的高保真 Word 报告 (.docx)',
    risk: 'write',
    requiresApproval: true,
    parameters: {
      type: 'object',
      properties: {
        target: { type: 'string', description: '生成的目标 Word 报告文件名（如 weekly-meeting-report.docx）' },
        title: { type: 'string', description: 'Word 报告主标题' },
        subtitle: { type: 'string', description: 'Word 报告副标题或编制信息' },
        sources: {
          type: 'array',
          items: { type: 'string' },
          description: '参考的工作区源材料文件名列表（如 meeting-notes.md, decisions.txt）',
        },
        sections: {
          type: 'array',
          description: '由模型撰写的结构化章节列表（包含 heading, paragraphs, table）',
        },
      },
    },
  };

  public canHandle(toolName: string): boolean {
    return toolName === this.name || toolName === 'workspace.write_report';
  }

  public async execute(
    _toolName: string,
    args: Record<string, unknown>,
    context: ToolContext,
  ): Promise<string> {
    const artifactName = (args.target as string) || 'weekly-meeting-report.docx';
    const customSections = Array.isArray(args.sections) ? (args.sections as RichDocxSection[]) : undefined;
    const title = (args.title as string) || 'Weekly Meeting Report';
    const subtitle = (args.subtitle as string) || 'Generated by Agent_XXXXX Production Office Engine';

    let docx: Buffer;
    if (customSections && customSections.length > 0) {
      docx = await context.officeEngine.createRichWordDocument({
        title,
        subtitle,
        sections: customSections,
      });
    } else {
      const allWorkspaceFiles = context.sandbox.listFiles();
      const rawSources =
        Array.isArray(args.sources) && args.sources.length > 0
          ? (args.sources as string[]).map(String)
          : allWorkspaceFiles.filter((f) => f.endsWith('.md') || f.endsWith('.txt') || f.endsWith('.csv'));

      const sources = rawSources
        .filter((name) => context.sandbox.hasFile(name))
        .map((name) => context.documentEngine.readSource(name, context.sandbox.readFileBuffer(name)));

      let table: { headers: readonly string[]; rows: readonly (readonly string[])[] } | undefined;
      // 动态查找工作区中存在的表格数据源文件用于嵌入表格
      const tableSource =
        rawSources.find((name) => name.endsWith('.csv') || name.endsWith('.xlsx')) ||
        allWorkspaceFiles.find((name) => name.endsWith('.csv') || name.endsWith('.xlsx'));

      if (tableSource && context.sandbox.hasFile(tableSource)) {
        const type = tableSource.endsWith('.xlsx') ? 'xlsx' : 'csv';
        const parsed = await context.officeEngine.readTableData(
          context.sandbox.readFileBuffer(tableSource),
          type,
        );
        if (parsed.headers.length > 0) {
          table = {
            headers: parsed.headers,
            rows: parsed.rows.map((r) => parsed.headers.map((h) => String(r[h] ?? ''))),
          };
        }
      }

      const sections: RichDocxSection[] =
        sources.length > 0
          ? sources.map((s) => ({
              heading: `参考材料：${s.name}`,
              paragraphs: [s.text.slice(0, 500)],
            }))
          : [
              {
                heading: '项目概览与执行总结',
                paragraphs: ['当前工作区未指定独立参考文件，本报告基于当前执行上下文与结构化大纲生成。'],
              },
            ];

      if (table && tableSource) {
        sections.push({
          heading: `数据明细汇总 (${tableSource})`,
          paragraphs: [`下表为从工作区文件 ${tableSource} 提取并解析的明细数据：`],
          table,
        });
      }

      docx = await context.officeEngine.createRichWordDocument({
        title,
        subtitle,
        sections,
      });
    }

    context.sandbox.writeArtifactBuffer(artifactName, docx);
    context.verifyArtifact(context.thread.id, artifactName);
    return `成功整合材料并生成高保真结构化 Word 报告：${artifactName}（已完成物理证据链校验）`;
  }
}

export class WorkspaceReportToolHandler implements IToolHandler {
  public readonly name = 'workspace.write_report';
  public readonly definition: AgentToolDefinition = {
    name: 'workspace.write_report',
    description: '使用轻量文档引擎将工作区内的材料汇总生成 Word 报告 (.docx)',
    risk: 'write',
    requiresApproval: true,
  };

  public canHandle(toolName: string): boolean {
    return toolName === 'workspace.write_report' || toolName === 'workspace.report';
  }

  public execute(
    _toolName: string,
    args: Record<string, unknown>,
    context: ToolContext,
  ): string {
    const artifactName = (args.target as string) || 'weekly-meeting-report.docx';
    const allFiles = context.sandbox.listFiles();
    const sourceNames = allFiles.filter(
      (name) => name.endsWith('.md') || name.endsWith('.txt') || name.endsWith('.csv'),
    );
    const sources = sourceNames.map((name) =>
      context.documentEngine.readSource(name, context.sandbox.readFileBuffer(name)),
    );
    const report = context.documentEngine.createDocx({
      title: (args.title as string) || 'Weekly Meeting Report',
      sources,
    });
    context.sandbox.writeArtifactBuffer(artifactName, report);
    return `${artifactName} was created successfully in the workspace`;
  }
}

