import { describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { ProductionOfficeEngine } from '../src/runtime/office-engine.js';
import { EvidenceVerifier } from '../src/runtime/verifier.js';
import { AppServer } from '../src/runtime/app-server.js';
import type { AnyRuntimeEvent, Plan, PlanStep } from '../src/runtime/protocol.js';
import type { ModelProvider } from '../src/runtime/model-provider.js';

function approvalIdFor(events: readonly AnyRuntimeEvent[]): string {
  const approvalEvent = events.find((event) => event.type === 'approval.requested');
  if (!approvalEvent || approvalEvent.type !== 'approval.requested') {
    throw new Error('missing approval.requested event');
  }
  return approvalEvent.payload.id;
}

function createOfficeWorkspace(): string {
  const root = mkdtempSync(join(tmpdir(), 'office-test-'));
  writeFileSync(
    join(root, 'meeting-notes.md'),
    '# Q3 Strategy Review\nFocus on enterprise customers and AI agent reliability.\n',
    'utf8',
  );
  writeFileSync(join(root, 'decisions.txt'), 'Decision: Adopt direct Office OpenXML engine\nOwner: Tech Lead\n', 'utf8');
  writeFileSync(join(root, 'sales.csv'), 'region,revenue,deals\nEast,52000,12\nWest,48000,10\nNorth,36000,8\n', 'utf8');
  return root;
}

class FixedToolModel implements ModelProvider {
  public constructor(private readonly toolName: string) {}

  public proposePlan(input: { turnId: string } | string): Plan {
    const turnId = typeof input === 'string' ? input : input.turnId;
    const step: PlanStep = {
      id: 'step-1',
      title: `Execute ${this.toolName}`,
      toolName: this.toolName,
      risk: 'write',
      requiresApproval: true,
    };
    return {
      id: 'plan-1',
      turnId,
      steps: [step],
      status: 'proposed',
    };
  }
}

describe('ProductionOfficeEngine Seam Tests', () => {
  const engine = new ProductionOfficeEngine();
  const verifier = new EvidenceVerifier();

  it('creates an Excel workbook with styling, auto-width, and sum formulas, and passes xlsx verification', async () => {
    const buffer = await engine.createExcelWorkbook({
      title: 'Quarterly Sales',
      sheets: [
        {
          name: 'Q3 Sales',
          columns: [
            { header: 'Region', key: 'region' },
            { header: 'Revenue', key: 'revenue' },
            { header: 'Deals', key: 'deals' },
          ],
          rows: [
            { region: 'East', revenue: 52000, deals: 12 },
            { region: 'West', revenue: 48000, deals: 10 },
            { region: 'North', revenue: 36000, deals: 8 },
          ],
          includeTotalRow: true,
        },
      ],
    });

    expect(buffer.length).toBeGreaterThan(1000);
    expect(buffer.subarray(0, 4).toString('binary')).toBe('PK\x03\x04');

    const tempPath = join(tmpdir(), `test-sales-${Date.now()}.xlsx`);
    writeFileSync(tempPath, buffer);

    try {
      const result = verifier.verify({
        artifactPath: tempPath,
        requireXlsxStructure: true,
      });

      expect(result.status).toBe('VERIFIED');
      expect(result.checks.some((c) => c.name === 'xlsx_structure' && c.status === 'passed')).toBe(true);
    } finally {
      rmSync(tempPath, { force: true });
    }
  });

  it('parses CSV data into structured headers, typed numbers, and summary totals', async () => {
    const csvContent = Buffer.from('product,units,price\nWidget A,10,25.5\nWidget B,20,15.0\n', 'utf8');
    const parsed = await engine.readTableData(csvContent, 'csv');

    expect(parsed.headers).toEqual(['product', 'units', 'price']);
    expect(parsed.rows.length).toBe(2);
    expect(parsed.rows[0]).toEqual({ product: 'Widget A', units: 10, price: 25.5 });
    expect(parsed.rows[1]).toEqual({ product: 'Widget B', units: 20, price: 15 });
    expect(parsed.summary.totalRows).toBe(2);
    expect(parsed.summary.numericSums['units']).toBe(30);
    expect(parsed.summary.numericSums['price']).toBe(40.5);
  });

  it('creates a rich Word document with headings and styled tables, and passes docx verification', async () => {
    const docxBuffer = await engine.createRichWordDocument({
      title: 'Weekly Meeting Report',
      subtitle: 'Generated by Agent_XXXXX Production Office Engine',
      sections: [
        {
          heading: 'Executive Summary',
          paragraphs: ['All launch blockers have been resolved.', 'Ready for Friday deployment.'],
        },
        {
          heading: 'Performance Metrics',
          table: {
            headers: ['Metric', 'Target', 'Actual'],
            rows: [
              ['Uptime', '99.9%', '99.95%'],
              ['Latency', '< 200ms', '142ms'],
            ],
          },
        },
      ],
    });

    expect(docxBuffer.length).toBeGreaterThan(1000);
    expect(docxBuffer.subarray(0, 4).toString('binary')).toBe('PK\x03\x04');

    const tempDocxPath = join(tmpdir(), `test-doc-${Date.now()}.docx`);
    writeFileSync(tempDocxPath, docxBuffer);

    try {
      const result = verifier.verify({
        artifactPath: tempDocxPath,
        requireDocxStructure: true,
        requiredText: ['Weekly Meeting Report', 'Executive Summary', 'Uptime'],
      });

      expect(result.status).toBe('VERIFIED');
      expect(result.checks.some((c) => c.name === 'docx_structure' && c.status === 'passed')).toBe(true);
      expect(result.checks.some((c) => c.name === 'required_text:Weekly Meeting Report' && c.status === 'passed')).toBe(true);
    } finally {
      rmSync(tempDocxPath, { force: true });
    }
  });

  it('executes office.process_excel end-to-end in AppServer and produces verified sales-summary.xlsx', async () => {
    const workspaceRoot = createOfficeWorkspace();
    const server = new AppServer({
      modelProvider: new FixedToolModel('office.process_excel'),
    });

    try {
      const thread = server.createThread({
        workspaceId: 'office-excel-test',
        workspaceRoot,
      });

      const turn = await server.startTurnAsync({
        threadId: thread.id,
        input: '汇总销售数据并生成 Excel 表格',
      });

      const events = server.listEvents(thread.id);
      const approvalId = approvalIdFor(events);

      await server.respondApprovalAsync({
        approvalId,
        decision: 'approved',
      });

      const finalTurn = server.getTurn(turn.id);
      expect(finalTurn.status).toBe('completed');

      const allEvents = server.listEvents(thread.id);
      const eventTypes = allEvents.map((e) => e.type);
      expect(eventTypes).toContain('tool.completed');
      expect(eventTypes).toContain('artifact.verified');

      const verificationEvent = allEvents.find((e) => e.type === 'artifact.verified');
      expect(verificationEvent).toBeDefined();
      if (verificationEvent && verificationEvent.type === 'artifact.verified') {
        expect(verificationEvent.payload.artifactName).toBe('sales-summary.xlsx');
        expect(verificationEvent.payload.status).toBe('verified');
      }
    } finally {
      rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('executes office.generate_word_report end-to-end in AppServer and produces verified weekly-meeting-report.docx', async () => {
    const workspaceRoot = createOfficeWorkspace();
    const server = new AppServer({
      modelProvider: new FixedToolModel('office.generate_word_report'),
    });

    try {
      const thread = server.createThread({
        workspaceId: 'office-word-test',
        workspaceRoot,
      });

      const turn = await server.startTurnAsync({
        threadId: thread.id,
        input: '整理会议材料并生成精美 Word 周报',
      });

      const events = server.listEvents(thread.id);
      const approvalId = approvalIdFor(events);

      await server.respondApprovalAsync({
        approvalId,
        decision: 'approved',
      });

      const finalTurn = server.getTurn(turn.id);
      expect(finalTurn.status).toBe('completed');

      const allEvents = server.listEvents(thread.id);
      const eventTypes = allEvents.map((e) => e.type);
      expect(eventTypes).toContain('tool.completed');
      expect(eventTypes).toContain('artifact.verified');

      const verificationEvent = allEvents.find((e) => e.type === 'artifact.verified');
      expect(verificationEvent).toBeDefined();
      if (verificationEvent && verificationEvent.type === 'artifact.verified') {
        expect(verificationEvent.payload.artifactName).toBe('weekly-meeting-report.docx');
        expect(verificationEvent.payload.status).toBe('verified');
      }
    } finally {
      rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });
});
